### ISSUE TITLE
Handle parallel editing 

### ISSUE THREAD

**Issue by Oremountainflorian** [humhub/wiki#113]
### Problem description 

At the moment two ore more persons can edit a wiki entry at the same time without noticing it. The first person saves and the wiki entry updates. Then the second person saves and simply overwrites the content of another person. Both without even noticing it. In the edit history there is no color highlighting who changed what from one version to another so it's even harder to see what happend.

### Possible solution

I guess the easiest solution is to block the edit button (you can see how's editing, to ask this person in case the he/she finished but neither saved nor closed the tab). 

### Alternative solution

Another solution could be the implementation and displaying of at least warning messages to all participants. (1) When starting to edit (2) When saving.

(1) You should get noticed, that someone else (with user name?) is already editing the entry. This should also show up to the person who initially started to edit. Maybe these persons can talk to each other to avoid redundant work. 

(2) When the first person saves, he/she should also receive a warning message that someone else (user name) is still editing. If the content has changed because someone saved first, the person who saves second should get noticed that the content changed meanwhile. 

---
I'd be really glad if you could solve this problem in a future version!

**Comment by yurabakhtin** [comment]
@luke- I think it can be implemented with steps:

- On load edit form we should create a hidden input with last updated data like this `<input type="hidden" name="lastUpdatedAt" value="<?= $model->content->updated_at ?>">`,
- On save action we can compare the submitted value `lastUpdatedAt` with value from DB, if they are different we display a warning message like:
  - "You are updating a not the latest version, please press "Save" again to overwrite the changes from '2021-07-21 14:30:10' made by 'User name'." and on next press "Save" we just force the save action,
  - or "..., please confirm you want to override that." + checkbox to confirm like "[√] I confirm to overwrite the changes from '2021-07-21 14:30:10' made by 'User name'.";
  - Also at this step we should store what version we can override on next submit, i.e. we should update the hidden input `lastUpdatedAt` with new value from DB so on next submit we can force only the version with date `lastUpdatedAt` in order to don't overwrite newest version while user thinks during time between first and second submits.

**Comment by luke-** [comment]
@yurabakhtin I think the steps are quite good. Instead of the "updatedAt" you could also use with the "wiki_page_revision.id". But feel free to choose which field you want to use.

A confirm checkbox that appears then, I also find great.

Maybe you could add a link (new window), which shows the new diff feature of the versions?

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/wiki/pull/196:

![confirm_wiki_latest_revision](https://user-images.githubusercontent.com/6995524/126677528-42bd33c2-92a1-45bd-a8cf-2da0f79d5dfb.jpg)

**Comment by luke-** [comment]
@yurabakhtin Wow, looks nice! Can you please also add some acceptance tests for this?

**Comment by Oremountainflorian** [comment]
@yurabakhtin Looks super good! Thankyou! 

Anyways, I have some questions on your PR

(1) To which time / state does "Jul 22, 2021 - 7:42 PM" refer to? To the moment in time when Sara Schuster 

- opened the older version
- saved it

Maybe their could be a distinction between these two states

In case of the first, 

- will Sara be noticed (in real-time) that her version will be overwritten?
- or generally, what does she see above when a second person joins in?

(2) Is the status above updated in real-time? So for example when Sara aborts the editing without saving, does the box vanish?

(3) What happens if a third person comes into game? Do the boxes above refer to the person who started editing as the last? 

(4) Just a small grammar thing, maybe it's more correct to say: "You're about to edit an outdated version, please confirm that you want to overwrite the changes made in the meantime since you started to edit the page."

**Comment by luke-** [comment]
@Oremountainflorian To answer your questions:

1.) It's the date/time of the latest saved version which will overwritten.
3.) It's always shows the latest saved version.
4.) Thanks, @yurabakhtin can you change the text

Of course there is still room for improvement, but this is a first important step :-)

**Comment by yurabakhtin** [comment]
@luke- 

> Can you please also add some acceptance tests for this?

I don't find how it is possible to open two browser tabs by two different users on acceptance test in order to simulate this new implemented feature.

I just test this by API test here https://github.com/humhub/wiki/pull/196/commits/c43b52d372ee507771492a4835a2ee5f563129e8

> @yurabakhtin can you change the text

Commit https://github.com/humhub/wiki/pull/196/commits/ba55b577eabf923ccbd072d235c3db519e07abf5

**Comment by luke-** [comment]
@yurabakhtin ok thanks!

**Comment by Oremountainflorian** [comment]
@luke- 

Of course! Just wanted to clarify some small things I didn't get directly, but most of it due to ambiguous labeling, which could be solved easily by editing the text. 

"Sara Schuster saved a newer version at ... 7:42 pm by after you started editing the page. This means you can't see the changes made and you're going to overwrite these changes by saving the page."

All the other things are just ideas for future improvements. We've been waiting longingly for this PR so we really appreciate the first steps made!

**Comment by luke-** [comment]
Ok, thank you!

@Semir1212 Can you please also have a look at the text.

**Comment by Semir1212** [comment]
@yurabakhtin A large warning box is sufficient, the editor and the options on the side are not necessary here. 

![Edit1](https://user-images.githubusercontent.com/38326726/127125606-2ecc5e38-dc85-4c9b-9188-7d561654f78f.jpg)

WARNING: Another user has updated this page since you have started editing it. Please confirm that you want to overwrite those changes. Compare versions: Link

Checkbox: Overwrite all changes made by User XXX on Date/Time YYY

Button 1: Overwrite (save and jump to view of the page)
Button 2: Back (jump back to editing)
Button 3: Discard my changes (jump to view of the page)

**Comment by luke-** [comment]
@Semir1212 Thanks!

**Comment by yurabakhtin** [comment]
@Semir1212 @luke- PR https://github.com/humhub/wiki/pull/197:

<img width="1157" alt="confirm_page" src="https://user-images.githubusercontent.com/6995524/128023630-16a97766-6784-4ffc-b5c1-2a0408252867.png">

**Comment by luke-** [comment]
@yurabakhtin Thanks! I have improved the formatting a bit but works well!
