### ISSUE TITLE
Wiki-Tree closed opens again after reload

### ISSUE THREAD

**Issue by JK742020** [humhub/wiki#148]
If I have a category and there are let's say 20 wiki pages inside it would be great to have the category closed in the wiki tree of main-page when desired. But if I close one category and reload page the category is opened again. Why do I have the possibility to close it when it will be opened again automatically?
Thanks!

**Comment by Oremountainflorian** [comment]
We also would really appreciate seeing this feature implemented because we have too many wikipages and it can be really annoying to scroll down when you search sth.

An easy solution could be introducing a tick box "fold/unfold category by default" for space admins when you open a category page within the wiki.

**Comment by JK742020** [comment]
Or just keep it the way you left it for next time you open the wiki again. This will be different from user to user. I am not really familiar with coding, but couldn't this be solved with a cookie?

**Comment by lokulluz** [comment]
Any news here?

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/wiki/pull/178: I have implemented this by storing the folding state per User in the db table `contentcontainer_setting` with name like `wiki.foldedCategory.123` where `123` is ID of the wiki category.
