### ISSUE TITLE
Display Last Editor Instead of Original Creator for Wiki Entries

### ISSUE THREAD

**Issue by tsfuchs** [humhub/wiki#339]
Unfortunately, for wiki entries, the original creator of an entry is still displayed even after many years, rather than the last editor. This means that after some years, a former employee is still listed on a wiki entry, even though the currently available article has nothing to do with the original entry and the content has completely changed. This is very confusing. 

Is there any way to adjust this? Doesn't it make more sense to display the last editor of an article instead of the original creator?

**Comment by marc-farre** [comment]
It would also be confusing to show the last editor because:
- on all HumHub, we display the content creator (posts, files, etc.)
- sometimes, a wiki page is created by someone, and an admin make a small change (spellchecking, etc.): the main author remains the content creator, not the admin

But you could use the ["Move content and users" module](https://marketplace.humhub.com/module/move-content/description) to change the all the content ownership of your former employee.
